name: Run Testing
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    # services:
    #   # Label used to access the service container
    #   redis:
    #     # Docker Hub image
    #     image: redis
    #     # Set health checks to wait until redis has started
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 6379:6379

    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 6379
          slave1-port: 6380
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run Tests
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
